language: ruby
os:
  - linux
  - osx
rvm:
  - 1.9
  - 2.0
  - 2.1
  - 2.2
  - 2.3.0
  - rbx-2
  - rbx-3.26
matrix:
  include:
    - rvm: &jruby_1_7 jruby-19mode
      jdk: openjdk6
      os: linux
    - rvm: *jruby_1_7
      jdk: openjdk7
      os: linux
    - rvm: *jruby_1_7
      jdk: oraclejdk7
      os: linux
    - rvm: *jruby_1_7
      jdk: oraclejdk8
      os: linux
    - rvm: &jruby_9_0 jruby-9.0.5.0
      jdk: openjdk6
      os: linux
    - rvm: *jruby_9_0
      jdk: openjdk7
      os: linux
    - rvm: *jruby_9_0
      jdk: oraclejdk7
      os: linux
    - rvm: *jruby_9_0
      jdk: oraclejdk8
      os: linux
    - rvm: *jruby_1_7
      os: osx
    - rvm: *jruby_9_0
      os: osx
  allow_failures:
    - rvm: 2.2 # Not available on Travis CI yet
      os: osx
    - rvm: 2.3.0 # Not available on Travis CI yet
      os: osx
    - rvm: *jruby_1_7 # Not available on Travis CI yet
      os: osx
    - rvm: *jruby_9_0 # JRuby 9.x does not support OpenJDK 6
      jdk: openjdk6

before_install:
  - gem install bundler
